export const CHANGE_CATLIST_CATEGORY = "playlist/CHANGE_CATLIST_CATEGORY";
export const CHANGE_HOT_COMMEND = "playlist/CHANGE_HOT_COMMEND";
export const CHANGE_LOADING = "playlist/CHANGE_LOADING";

export const CHANGE_PLAYLIST_DETAIL = "playlistDetails/CHANGE_PLAYLIST_DETAIL";
