export const CHANGE_DJ_CATEGORY = "djradio/CHANGE_DJ_CATEGORY ";
export const CHANGE_DJ_RECOMMEND = "djradio/CHANGE_DJ_RECOMMEND";
export const CHANGE_DJ_PROGRAM_TOP = "djradio/CHANGE_DJ_PROGRAM_TOP";
export const CHANGE_DJ_HOT_RADIO = "djradio/CHANGE_DJ_HOT_RADIO";
